# Generated by Django 5.1.3 on 2024-12-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nivel_satisfaccion',
            field=models.IntegerField(choices=[(1, 'Muy insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy satisfecho')]),
        ),
    ]
