# Generated by Django 5.1.3 on 2024-12-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cliente_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F'), ('Otro', 'O')], max_length=10),
        ),
    ]
